#ifndef CIRCLERECOGNIZER_GLOBAL_H
#define CIRCLERECOGNIZER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CIRCLERECOGNIZER_LIBRARY)
#  define CIRCLERECOGNIZERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CIRCLERECOGNIZERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CIRCLERECOGNIZER_GLOBAL_H
