#ifndef RECTANGLERECOGNIZER_GLOBAL_H
#define RECTANGLERECOGNIZER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(RECTANGLERECOGNIZER_LIBRARY)
#  define RECTANGLERECOGNIZERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define RECTANGLERECOGNIZERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // RECTANGLERECOGNIZER_GLOBAL_H
